In [3]:
import pandas as pd

data = pd.read_csv("data.csv")
data

        Condition  Trial  P1_mV   T1_mV  P2_mV   T2_mV     Gamma
0          Normal      1  131.2  1495.2   31.1  1494.7  1.320712
1          Normal      2  126.4  1495.1   29.7  1494.6  1.316685
2          Normal      3  127.6  1495.1   29.8  1494.7  1.314267
3          Normal      4  122.9  1495.1   27.8  1494.8  1.301165
4          Normal      5  130.8  1495.4   30.5  1495.0  1.313868
5          Normal      6  123.9  1495.4   29.3  1495.0  1.319167
6          Normal      7  126.4  1495.5   31.6  1495.1  1.343696
7          Normal      8  135.0  1495.6   33.5  1495.1  1.340999
8          Normal      9  127.5  1495.6   28.7  1495.1  1.299597
9          Normal     10  127.0  1495.4   30.4  1494.9  1.324530
10   Long Release      1  137.0  1495.5   19.1  1495.0  1.167462
11   Long Release      2  131.6  1495.6   17.8  1495.2  1.161481
12   Long Release      3  139.2  1495.6   20.2  1495.1  1.175559
13   Long Release      4  127.5  1495.5   18.7  1495.1  1.177270
14   Long Release      5  125.3  1495.5   20.4  1495.0  1.200470
15  Short Release      1  131.8  1495.5   52.8  1495.1  1.689973
16  Short Release      2  134.8  1495.4   45.4  1495.0  1.524637
17  Short Release      3  125.8  1495.0   48.7  1494.6  1.651165
18  Short Release      4  124.0  1494.9   35.1  1494.4  1.406866
19  Short Release      5  128.1  1494.8   60.2  1494.4  1.914462